batch1:
	python train.py --model leNet
	python train.py --model tsjs_tutorial
	python train.py --model mini_mobilenet

batch2:
	python train.py --model mini --batch-size 64
	python train.py --model keras_tutorial
	python train.py --model chat_gpt5
