batch1:
	python train.py --model geeks_for_geeks
	python train.py --model tsjs_tutorial
	python train.py --model mini_mobilenet

batch2:
	python train.py --model chat_gpt5
	python train.py --model mini

batch3:
	python train.py --model leNet
	python trian.py --model keras_tutorial
