logsBucket: 'NONE'

steps:
- name: 'docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/mingli202/mathracer-web', './frontend'] 
- name: 'docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/mingli202/mathracer-server', './backend'] 

images:
  - 'gcr.io/$PROJECT_ID/mingli202/mathracer-web'
  - 'gcr.io/$PROJECT_ID/mingli202/mathracer-server'
