steps:
- name: 'docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/mingli202/mathracer-web', './frontend'] 
  env:
  - 'NEXT_PUBLIC_API_URL=${_NEXT_PUBLIC_API_URL}'
  waitFor: ['-']
  id: 'build-web'

- name: 'docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/mingli202/mathracer-server', './backend'] 
  env:
  - 'FRONTEND_URL=${_FRONTEND_URL}'
  waitFor: ['-']
  id: 'build-server'

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args:
    - 'run'
    - 'services'
    - 'update'
    - 'mathracer-web'
    - '--region'
    - '${_REGION}'
    - '--image'
    - 'gcr.io/$PROJECT_ID/mingli202/mathracer-web:latest'
  waitFor: 
    - 'build-web'

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args:
    - 'run'
    - 'services'
    - 'update'
    - 'mathracer-server'
    - '--region'
    - '${_REGION}'
    - '--image'
    - 'gcr.io/$PROJECT_ID/mingli202/mathracer-server:latest'
  waitFor: 
    - 'build-server'


images:
  - 'gcr.io/$PROJECT_ID/mingli202/mathracer-web'
  - 'gcr.io/$PROJECT_ID/mingli202/mathracer-server'


options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
