steps:
- name: 'docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/mingli202/mathracer-web:$COMMIT_SHA', './frontend'] 
  env:
  - 'NEXT_PUBLIC_API_URL=${_NEXT_PUBLIC_API_URL}'
  waitFor: ['-']
  id: 'build-web'

- name: 'docker'
  args: ['push', 'gcr.io/$PROJECT_ID/mingli202/mathracer-web:$COMMIT_SHA']
  waitFor: ['build-web']
  id: 'push-web'

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args:
    - 'run'
    - 'services'
    - 'update'
    - 'mathracer-web'
    - '--region'
    - '${_REGION}'
    - '--image'
    - 'gcr.io/$PROJECT_ID/mingli202/mathracer-web:$COMMIT_SHA'
    - '--platform'
    - 'managed'
  waitFor: 
    - 'push-web'

- name: 'docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/mingli202/mathracer-server:$COMMIT_SHA', './backend'] 
  env:
  - 'FRONTEND_URL=${_FRONTEND_URL}'
  waitFor: ['-']
  id: 'build-server'

- name: 'docker'
  args: ['push', 'gcr.io/$PROJECT_ID/mingli202/mathracer-server:$COMMIT_SHA']
  waitFor: ['build-server']
  id: 'push-server'

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args:
    - 'run'
    - 'services'
    - 'update'
    - 'mathracer-server'
    - '--region'
    - '${_REGION}'
    - '--image'
    - 'gcr.io/$PROJECT_ID/mingli202/mathracer-server:$COMMIT_SHA'
    - '--platform'
    - 'managed'
  waitFor: 
    - 'push-server'


images:
  - 'gcr.io/$PROJECT_ID/mingli202/mathracer-web:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/mingli202/mathracer-server:$COMMIT_SHA'


options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
