steps:
- name: 'docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/mingli202/mathracer-web', './frontend'] 
  env:
  - 'NEXT_PUBLIC_API_URL=${_NEXT_PUBLIC_API_URL}'
  waitFor: ['-']
  id: 'build-web'

- name: 'docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/mingli202/mathracer-server', './backend'] 
  env:
  - 'FRONTEND_URL=${_FRONTEND_URL}'
  waitFor: ['-']
  id: 'build-server'

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args:
    - 'run'
    - 'deploy'
    - 'mathracer-web'
    - '--image'
    - 'gcr.io/$PROJECT_ID/mingli202/mathracer-web:latest'
    - '--region'
    - '${_REGION}'
    # - '--allow-unauthenticated'
    # - '--memory'
    # - '512Mi'
    # - '--cpu'
    # - '1'
    # - '--min-instances'
    # - '0'
    # - '--set-env-vars'
    # - 'SERVER_URL=${_SERVER_URL},RSA_PUBLIC_KEY=${_RSA_PUBLIC_KEY},RSA_PRIVATE_KEY=${_RSA_PRIVATE_KEY}'
  waitFor: 
    - 'build-web'

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args:
    - 'run'
    - 'deploy'
    - 'mathracer-server'
    - '--image'
    - 'gcr.io/$PROJECT_ID/mingli202/mathracer-server:latest'
    - '--region'
    - '${_REGION}'
  waitFor: 
    - 'build-server'


images:
  - 'gcr.io/$PROJECT_ID/mingli202/mathracer-web'
  - 'gcr.io/$PROJECT_ID/mingli202/mathracer-server'


options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
