steps:
- name: 'docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/mingli202/mathracer-web', './frontend'] 
  env:
  - 'NEXT_PUBLIC_API_URL=${_NEXT_PUBLIC_API_URL}'
- name: 'docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/mingli202/mathracer-server', './backend'] 

images:
  - 'gcr.io/$PROJECT_ID/mingli202/mathracer-web'
  - 'gcr.io/$PROJECT_ID/mingli202/mathracer-server'


options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
