steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: ['-c', 'docker login --username=$$USERNAME --password=$$PASSWORD']
  secretEnv: ['USERNAME', 'PASSWORD']

- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
        DOCKER_BUILDKIT=1 docker build \
        --build-arg WEBAPP_URLS=${_WEBAPP_URLS} \
        -t $$USERNAME/mathracer-server:$COMMIT_SHA \
        ./backend
  env:
    - 'WEBAPP_URLS=${_WEBAPP_URLS}'
  secretEnv: ['USERNAME']

- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: ['-c', 'docker push $$USERNAME/mathracer-server:$COMMIT_SHA']
  secretEnv: ['USERNAME']

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
        gcloud run services update mathracer-server \
        --region ${_REGION} \
        --image $$USERNAME/mathracer-server:$COMMIT_SHA \
        --platform managed
  secretEnv: ['USERNAME']

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET

availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/docker-username/versions/2
    env: 'USERNAME'
  - versionName: projects/$PROJECT_ID/secrets/docker-password/versions/1
    env: 'PASSWORD'
