steps:
- name: 'docker'
  args: ['login --username=$$USERNAME --password=$$PASSWORD']
  secretEnv: ['USERNAME', 'PASSWORD']

- name: 'docker'
  args:
    - 'build'
    - '-t'
    - '$$USERNAME/mathracer-server:$COMMIT_SHA'
    - '--build-arg'
    - 'WEBAPP_URLS=${_WEBAPP_URLS}'
    - './backend' 
  env:
    - 'WEBAPP_URLS=${_WEBAPP_URLS}'
  secretEnv: ['USERNAME']

- name: 'docker'
  args: ['push', '$$USERNAME/mathracer-server:$COMMIT_SHA']
  secretEnv: ['USERNAME']

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args:
    - 'run'
    - 'deploy'
    - 'mathracer-server'
    - '--region'
    - '${_REGION}'
    - '--image'
    - '$$USERNAME/mathracer-server:$COMMIT_SHA'
    - '--platform'
    - 'managed'
  secretEnv: ['USERNAME']

images:
  - 'gcr.io/$PROJECT_ID/mingli202/mathracer-server:$COMMIT_SHA'

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET

availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/docker-username/versions/2
    env: 'USERNAME'
  - versionName: projects/$PROJECT_ID/secrets/docker-password/versions/1
    env: 'PASSWORD'
