all: batch1 batch2

batch1:
	bun run src/index.ts --model LeNet
	bun run src/index.ts --model TfjsTutorial,
	bun run src/index.ts --model MobileNetMini

batch2:
	bun run src/index.ts --model Mini
	bun run src/index.ts --model KerasTutorial
	bun run src/index.ts --model ChatGpt5
